# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Weewx
version: "1.1.0"
slug: weewx
description: Addon for the weewx server
url: "https://github.com/dalethestirling/hassio-addons/tree/main/weewx"
arch:
  - aarch64
  # - amd64
init: false
map:
  - share:rw
  - addon_config:rw
options:
  location: null
schema:
  location: "str"
image: "ghcr.io/dalethestirling/{arch}-addon-weewx"
