# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Weewx
version: "1.1.5"
slug: weewx
description: Addon for the weewx server
url: "https://github.com/dalethestirling/hassio-addons/tree/main/weewx"
arch:
  - aarch64
  # - amd64
discovery:
  - weewx
init: false
map:
  - share:rw
  - addon_config:rw
options:
  location: null
  altitude: null
  altitude_format: null
  latitude: null
  longitude: null
  display_units: null
schema:
  location: str
  altitude: int
  altitude_format: list(foot|meter)
  latitude: float
  longitude: float
  display_units: list(us|metricwx|metric)
ports:
  80/tcp: 48080
ports_description:
  80/tcp: Intercepter port
image: "ghcr.io/dalethestirling/{arch}-addon-weewx"
